# This is a basic workflow to help you get started with Actions

name: Build YodaUsesArch ISO automagically.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: pacman-key --init
      - run: pacman --noconfirm -Sy archlinux-keyring
      - run: pacman -Sy; pacman --noconfirm -S git archiso
      - run: mkdir ../work; mkdir ../out;  mkarchiso -v -w ../work/ -o ../out/ ./
      - run: cp -r ../out /tmp/
      - run: cp -r ../out /tmp/out
      - name: Publish New Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: /tmp/out/*.iso
          asset_name: yodalinux.iso
          tag: ${{ github.ref }}
          overwrite: true
          body: "Released the ISO, Yoda has"
          file_glob: true
